//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dive into the soulful world of ragas, rhythms, and traditions. Explore how music connects us across generations..
        /// </summary>
        internal static string HomePageSubSubTitle {
            get {
                return ResourceManager.GetString("HomePageSubSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the world of classical music.
        /// </summary>
        internal static string HomePageSubTitle {
            get {
                return ResourceManager.GetString("HomePageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the world of Classical Music.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string Menu_Artist {
            get {
                return ResourceManager.GetString("Menu_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compositions.
        /// </summary>
        internal static string Menu_Compositions {
            get {
                return ResourceManager.GetString("Menu_Compositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string Menu_Contact {
            get {
                return ResourceManager.GetString("Menu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Menu_Download {
            get {
                return ResourceManager.GetString("Menu_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Menu_Hello {
            get {
                return ResourceManager.GetString("Menu_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOff.
        /// </summary>
        internal static string Menu_LogOff {
            get {
                return ResourceManager.GetString("Menu_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raaga.
        /// </summary>
        internal static string Menu_Raag {
            get {
                return ResourceManager.GetString("Menu_Raag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Menu_Register {
            get {
                return ResourceManager.GetString("Menu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signin.
        /// </summary>
        internal static string Menu_Signin {
            get {
                return ResourceManager.GetString("Menu_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tala.
        /// </summary>
        internal static string Menu_Tala {
            get {
                return ResourceManager.GetString("Menu_Tala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thaat.
        /// </summary>
        internal static string Menu_Thaat {
            get {
                return ResourceManager.GetString("Menu_Thaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raag of the Day.
        /// </summary>
        internal static string SectionHead_1 {
            get {
                return ResourceManager.GetString("SectionHead_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist of the Day.
        /// </summary>
        internal static string SectionHead_2 {
            get {
                return ResourceManager.GetString("SectionHead_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest additions to this website.
        /// </summary>
        internal static string SectionHead_3 {
            get {
                return ResourceManager.GetString("SectionHead_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest additions to the website.
        /// </summary>
        internal static string SectionHead_4 {
            get {
                return ResourceManager.GetString("SectionHead_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classical Music.
        /// </summary>
        internal static string WebTitle {
            get {
                return ResourceManager.GetString("WebTitle", resourceCulture);
            }
        }
    }
}
