//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalMusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppImage
    {
        public int ID { get; set; }
        public string Image_For { get; set; }
        public Nullable<int> Image_For_Id { get; set; }
        public string ImageUrl { get; set; }
        public string ImageUrl_mid { get; set; }
        public string ImageUrl_small { get; set; }
    }
}
