//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalMusicApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IndianClassicalMusicEntities : DbContext
    {
        public IndianClassicalMusicEntities()
            : base("name=IndianClassicalMusicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppResource> AppResources { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<ArtistRole> ArtistRoles { get; set; }
        public virtual DbSet<Composition> Compositions { get; set; }
        public virtual DbSet<CompositionAlap> CompositionAlaps { get; set; }
        public virtual DbSet<CompositionNotation> CompositionNotations { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<MusicalInstrument> MusicalInstruments { get; set; }
        public virtual DbSet<MusicType> MusicTypes { get; set; }
        public virtual DbSet<Performance> Performances { get; set; }
        public virtual DbSet<Raaga> Raagas { get; set; }
        public virtual DbSet<Recording> Recordings { get; set; }
        public virtual DbSet<Tala> Talas { get; set; }
        public virtual DbSet<Thaat> Thaats { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<AppImage> AppImages { get; set; }
        public virtual DbSet<AppDocuments> AppDocuments { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    }
}
