//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalMusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Composition()
        {
            this.CompositionAlaps = new HashSet<CompositionAlap>();
            this.CompositionNotations = new HashSet<CompositionNotation>();
            this.Performances = new HashSet<Performance>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Lyrics { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> RagaID { get; set; }
        public Nullable<int> TalaID { get; set; }
        public Nullable<int> ComposerID { get; set; }
        public Nullable<int> MovieID { get; set; }
        public Nullable<int> MusicTypeID { get; set; }
        public Nullable<int> AppResourceID { get; set; }
    
        public virtual AppResource AppResource { get; set; }
        public virtual Artist Artist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompositionAlap> CompositionAlaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompositionNotation> CompositionNotations { get; set; }
        public virtual Language Language { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual MusicType MusicType { get; set; }
        public virtual Raaga Raaga { get; set; }
        public virtual Tala Tala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Performance> Performances { get; set; }
    }
}
