//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalMusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompositionAlap
    {
        public int ID { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string Notations { get; set; }
        public Nullable<int> CompositionID { get; set; }
        public Nullable<int> AppResourceID { get; set; }
    
        public virtual AppResource AppResource { get; set; }
        public virtual Composition Composition { get; set; }
    }
}
