//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalMusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicalInstrument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusicalInstrument()
        {
            this.Performances = new HashSet<Performance>();
        }
    
        public int ID { get; set; }
        public string MusicalInstrumentName { get; set; }
        public string MusicalInstrumentDesc { get; set; }
        public Nullable<int> AppResourceID { get; set; }
    
        public virtual AppResource AppResource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Performance> Performances { get; set; }
    }
}
