//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalMusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusicType()
        {
            this.Compositions = new HashSet<Composition>();
            this.Raagas = new HashSet<Raaga>();
            this.Thaats = new HashSet<Thaat>();
        }
    
        public int ID { get; set; }
        public string MusicTypeName { get; set; }
        public string MusicTypeDesc { get; set; }
        public Nullable<int> AppResourceID { get; set; }
    
        public virtual AppResource AppResource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Composition> Compositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Raaga> Raagas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thaat> Thaats { get; set; }
    }
}
