//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalMusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Performance()
        {
            this.Recordings = new HashSet<Recording>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> PerformanceDate { get; set; }
        public string Venue { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public Nullable<int> CompositionID { get; set; }
        public Nullable<int> MusicalInstrumentID { get; set; }
        public string Notes { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Composition Composition { get; set; }
        public virtual MusicalInstrument MusicalInstrument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recording> Recordings { get; set; }
    }
}
