//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalMusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raaga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Raaga()
        {
            this.Compositions = new HashSet<Composition>();
        }
    
        public int ID { get; set; }
        public string RaagaName { get; set; }
        public string RaagaTime { get; set; }
        public string Mood { get; set; }
        public string Aroh { get; set; }
        public string Avroh { get; set; }
        public string Pakad { get; set; }
        public string Vadi { get; set; }
        public string Samvadi { get; set; }
        public string Swara { get; set; }
        public Nullable<int> ThaatID { get; set; }
        public Nullable<int> MusicTypeID { get; set; }
        public Nullable<int> AppResourceID { get; set; }
        public string RaagaDesc { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual AppResource AppResource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Composition> Compositions { get; set; }
        public virtual MusicType MusicType { get; set; }
        public virtual Thaat Thaat { get; set; }
    }
}
