//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalMusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recording
    {
        public int ID { get; set; }
        public string FilePath { get; set; }
        public string RecordingFormat { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> PerformanceID { get; set; }
    
        public virtual Performance Performance { get; set; }
    }
}
