//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalMusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thaat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thaat()
        {
            this.Raagas = new HashSet<Raaga>();
        }
    
        public int ID { get; set; }
        public string ThaatName { get; set; }
        public string ThaatDesc { get; set; }
        public Nullable<int> MusicTypeID { get; set; }
        public Nullable<int> AppResourceID { get; set; }
        public string Aroh { get; set; }
        public string Avroh { get; set; }
    
        public virtual AppResource AppResource { get; set; }
        public virtual MusicType MusicType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Raaga> Raagas { get; set; }
    }
}
